name: qthello 
version: '0.1' 
summary: a demo for qt hello app
description: |
  This is a qt app demo

grade: stable 
confinement: strict 

apps:
  qthello:
    command: desktop-launch $SNAP/opt/myapp/qtapp
    plugs: [home, unity7, x11]

parts:
  project:
    plugin: qmake
    source: .
    qt-version: qt5
    project-files: [qtapp.pro]
    install: |
      install -d $SNAPCRAFT_PART_INSTALL/opt/myapp
      install qtapp $SNAPCRAFT_PART_INSTALL/opt/myapp/qtapp

  integration:
    plugin: nil
    stage-packages:
     - libc6
     - libstdc++6
     - libc-bin
    after: [desktop-qt5]
